# Generated by Django 3.0.8 on 2020-07-21 06:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200720_2317'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
